spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CloudNative
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.cloudnativewebapplication.filter: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DEBUG
      hibernate:
        SQL: DEBUG